### ISSUE TITLE
subcon should be a Construct field

### ISSUE THREAD

**Issue by somerandomsequence** [all-umass/superman#3]
I get the following error using the latest 'master' branch, xylib-py, and metakit 2.4.9.7 (placed in local directory):

```
$ python scripts/convert_spectra.py 
Traceback (most recent call last):
  File "scripts/convert_spectra.py", line 5, in <module>
    from superman.file_io import parse_spectrum, write_opus, write_rruff
  File "/superman/superman/file_io/__init__.py", line 26, in <module>
    from .renishaw import parse_wxd
  File "/superman/superman/file_io/renishaw.py", line 131, in <module>
    Struct(Const('tag'/Int16ul, 5), 'value'/Float64l),
  File "/.local/lib/python2.7/site-packages/construct/core.py", line 1277, in __init__
    super(Const, self).__init__(subcon)
  File "/.local/lib/python2.7/site-packages/construct/core.py", line 287, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
```

I'm primarily interested in using supeman to parse wxd files from a Raman microscope, so any help you can provide would be much appreciated.

**Comment by perimosocordiae** [comment]
I think I may have fixed it, though I haven't verified locally. Let me know if it works for you now.

**Comment by somerandomsequence** [comment]
I can confirm that the master branch no longer has this problem. Thanks!
